
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: netpol-1
  namespace: test
spec: # bloc qui permet de laisser passer le container client
  ingress: # Ingress behaviour
  - from:
    - podSelector:
        matchLabels:
          run: client
  podSelector:
    matchLabels:
      run: nginx
  policyTypes:
  - Ingress

# Bloque tout
#  spec:
#  podSelector: {}  # no pods !!!
#  policyTypes:
#  - Ingress   # traffic IN
#  - Egress    # traffic OUT