apiVersion: v1 # the api version to use
kind: Pod # for example: Pod
metadata:
  name: webservice01
spec:
  containers:
  - name: webby # name of container
    image: bchd.registry/alta3-webby # name of the image to use
    ports:
    - name: web # name for port mapping
      containerPort: 8888 # we mapped this with the port-forward command
      protocol: TCP # TCP or UDP

# apiVersion: v1
# kind: Pod
# metadata:
#   name: myfirstpod
# spec:
#   containers:
#   - name: webster
#     image: bchd.registry/alta3-webby
# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#container-v1-core
